// examples/react-app/src/Player.jsx
import "./Player.css";
import "@ezuikit/player-hls/dist/style/css.js";
import { useCallback, useEffect, useRef } from "react";
import HlsPlayer from "@ezuikit/player-hls";

function Player() {
  /** @type { React.MutableRefObject<HlsPlayer>} */
  const playerRef = useRef();
  const urlRef = useRef();
  const containerRef = useRef();
  const volumeRef = useRef();

  useEffect(() => {
    volumeRef.current.addEventListener("blur", (e) => {
      if (playerRef.current) {
        let value = (e.target.value || "").trim();
        if (value === "") {
          console.error("音量为空");
          return;
        }
        value = Number(value);
        if (value > 1 || value < 0) {
          console.error("音量设置错误， 取值范围在[0,1]");
          return;
        }

        value = parseInt((value * 100 + "").split(".")[0]) / 100; // 不使用 toFixed 是为了避免四舍五入问题
        playerRef.current.setVolume(value);
      } else {
        console.log("player 未初始化");
      }
    });
  }, []);

  const createPlayer = () => {
    const url = urlRef.current.value;
    if (!playerRef.current) {
      // 依赖的解码资源在 public 目录下 (必须的)
      playerRef.current = new HlsPlayer({
        id: "player-container",
        url,
        // decoderType: "soft",
        // 如果是萤石平台的ll-hls回放地址, 需要提供 accessToken， 为了方便暂停后重新回去新的地址进行播放， 不然会报 Missing accessToken
      });
      // 默认自动播放
      // playerRef.current.play();
      
      // v0.1.4
      playerRef.current.event.on("videoInfo", (info) => {
        console.log("videoInfo", info);
      });
    }
  };

  const handleInIt = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.destroy();
      playerRef.current = null;
    }
    createPlayer();
  }, []);

  const handlePlay = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.play();
    }
  }, []);

  const handlePause = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.pause();
    }
  }, []);

  const handleDestroy = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.destroy();
      playerRef.current = null;
    }
  }, []);

  const handleFullscreen = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.fullscreen();
    }
  }, []);

  const handleExitFullscreen = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.exitFullscreen();
    }
  }, []);

  const handleGetVersion = useCallback(() => {
    if (playerRef.current) {
      console.log(playerRef.current.getVersion());
    }
  }, []);

  return (
    <div>
      <div id="player-container" ref={containerRef}></div>
      <div>
        <div>
          <input
            style={{ width: 600 }}
            placeholder="输入播放地址"
            ref={urlRef}
            defaultValue="https://open.ys7.com/v3/openlive/L28647609_1_2.m3u8?expire=1764644823&id=915914456004136960&t=cbad467c0cc2dcafa9e8b663e1fcee506d0ad9863e931d77b4423a25a6e3130&ev=101&supportH265=1"
          />
        </div>
        <div>
          <button onClick={handleInIt}>init</button>
          <button onClick={handlePlay}>播放</button>
          <button onClick={handlePause}>暂停</button>
          <button onClick={handleFullscreen}>开启全屏</button>
          <button onClick={handleExitFullscreen}>取消全屏（ESC）</button>
          <button onClick={handleGetVersion}>获取版本</button>
          <button onClick={handleDestroy}>销毁</button>
        </div>
        <div>
          音量：
          <input ref={volumeRef} placeholder="0-1" />
        </div>
      </div>
    </div>
  );
}

export default Player;

// examples/with-vue2.5/src/components/Player.vue
<template>
  <div class="ezuikit-hls">
    <div>
      <div id="video-container" style="height: 400px"></div>
    </div>
    <div>
      <input v-model="url" placeholder="请输入视频 URL" style="width: 600px; margin-right: 8px;" />
      <button v-on:click="init">init</button>
      <button v-on:click="pause">pause</button>
      <button v-on:click="play">play</button>
      <button v-on:click="fullscreen">fullscreen</button>
      <button v-on:click="destroy">destroy</button>
    </div>
  </div>
</template>

<script>
import "@ezuikit/player-hls/dist/style/css.js";
import HlsPlayer from "@ezuikit/player-hls";
var player = null;

export default {
  name: "Player",
  props: {
    msg: String,
  },
  data() {
    return {
      url: "https://open.ys7.com/v3/openpb/llhls/BC7799091_1_1.m3u8?begin=20260716000000&end=20260716235959&expire=1784794232&id=997898038200520704&rec=cloud&t=814a7752e1cd06efaa7da5c607971669ba2c92ea11d9a695c428f017e9f83700&ev=101&ownerId=openteam&streamer=alicloud.ys7.com:32723&VideoType=2&StorageVersion=2&supportH265=1",
    };
  },
  mounted() {
    // this.init();
  },
  methods: {
    init() {
      if (player) {
        this.destroy();
      }
      // 依赖的解码资源在 public 目录下 (必须的)
      player = new HlsPlayer({
        id: "video-container", // 视频容器ID
        url: this.url,
        loggerOptions: {
          level: "WARN",
        },
        // decoderType: "soft",
        // 如果是萤石平台的ll-hls回放地址, 需要提供 accessToken， 为了方便暂停后重新回去新的地址进行播放， 不然会报 Missing accessToken
      });

      player.event.on("videoInfo", (info) => {
        console.warn("videoInfo: ", info)
      })
      // 默认自动播放
      // player.play()
      window.player = player;
    },
    play() {
      if(player)
        player.play()
    },
    pause() {
      if(player)
        player.pause();
    },
    fullscreen() {
      if(player) player.fullscreen(); // 8.2.0 新增, 老版本使用 fullScreen()
    },
    destroy() {
      if(player) {
        player.destroy()
        player = null;
      }
    },
  },
};
</script>
