// examples/vue-app/src/components/Player.vue
<script setup>
import "@ezuikit/player-hls/dist/style/css.js";
import { onBeforeUnmount, ref } from 'vue'

import HlsPlayer from '@ezuikit/player-hls';

let player = null
const url = ref('https://open.ys7.com/v3/openlive/L28647609_1_2.m3u8?expire=1764644823&id=9159144560046960&t=cbad467c0cc2dcafa9e8b663e1fcee506dc0ad9863e931d77b4423a25a6e3130&ev=101&supportH265=1')
const volume = ref(0)

const init = () => {
  if (player) {
    destroy()
  }

  const playUrl = url.value.trim()
  if (!playUrl) {
    console.error('播放地址不能为空')
    return
  }

  // 依赖的解码资源在 public 目录下 (必须的)
  /** @type {HlsPlayer} */
  player = new HlsPlayer({
    id: 'container',
    url: playUrl,
    // decoderType: "soft",
    // 如果是萤石平台的ll-hls回放地址, 需要提供 accessToken， 为了方便暂停后重新回去新的地址进行播放， 不然会报 Missing accessToken
  })
  // 默认自动播放
  // player.play()

  // v0.1.4
  player.event.on("videoInfo", (info) => {
    console.log("videoInfo", info);
  });
}

const play = () => {
  if (player) {
    player.play()
  }
}

const pause = () => {
  if (player) {
    player.pause()
  }
}

const fullscreen = () => {
  if (player) {
    player.fullscreen()
  }
}

const destroy = () => {
  if (player) {
    player.destroy()
    player = null
  }
}

const setVolume = () => {
  if (!player) {
    console.warn('播放器未初始化')
    return
  }

  let nextVolume = Number(volume.value)
  if (Number.isNaN(nextVolume) || nextVolume < 0 || nextVolume > 1) {
    console.error('音量范围应在 0 到 1 之间')
    return
  }

  nextVolume = Math.floor(nextVolume * 100) / 100
  volume.value = nextVolume
  player.setVolume(nextVolume)
}

onBeforeUnmount(() => {
  destroy()
})
</script>

<template>
  <div class="player-wrap">
    <div id="container"></div>

    <div class="controls-row">
      <input v-model="url" class="url-input" placeholder="请输入 m3u8 播放地址" />
      <button @click="init">初始化</button>
      <button @click="pause">暂停</button>
      <button @click="play">播放</button>
      <button @click="fullscreen">全屏</button>
      <button @click="destroy">销毁</button>
    </div>

    <div class="controls-row">
      <label for="volume-input">音量</label>
      <input
        id="volume-input"
        v-model.number="volume"
        class="volume-input"
        type="number"
        min="0"
        max="1"
        step="0.01"
        placeholder="0-1"
      />
      <button @click="setVolume">设置音量</button>
    </div>
  </div>
</template>

<style>
.player-wrap {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.controls-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  align-items: center;
}

.url-input {
  width: 600px;
  max-width: 100%;
}

.volume-input {
  width: 100px;
}

#container {
  width: 600px;
  height: 400px;
  background: #000;
}
</style>

// examples/react-app/src/Player.jsx
import "./Player.css";
import "@ezuikit/player-hls/dist/style/css.js";
import { useCallback, useEffect, useRef } from "react";
import HlsPlayer from "@ezuikit/player-hls";

function Player() {
  /** @type { React.MutableRefObject<HlsPlayer>} */
  const playerRef = useRef();
  const urlRef = useRef();
  const containerRef = useRef();
  const volumeRef = useRef();

  useEffect(() => {
    volumeRef.current.addEventListener("blur", (e) => {
      if (playerRef.current) {
        let value = (e.target.value || "").trim();
        if (value === "") {
          console.error("音量为空");
          return;
        }
        value = Number(value);
        if (value > 1 || value < 0) {
          console.error("音量设置错误， 取值范围在[0,1]");
          return;
        }

        value = parseInt((value * 100 + "").split(".")[0]) / 100; // 不使用 toFixed 是为了避免四舍五入问题
        playerRef.current.setVolume(value);
      } else {
        console.log("player 未初始化");
      }
    });
  }, []);

  const createPlayer = () => {
    const url = urlRef.current.value;
    if (!playerRef.current) {
      // 依赖的解码资源在 public 目录下 (必须的)
      playerRef.current = new HlsPlayer({
        id: "player-container",
        url,
        // decoderType: "soft",
        // 如果是萤石平台的ll-hls回放地址, 需要提供 accessToken， 为了方便暂停后重新回去新的地址进行播放， 不然会报 Missing accessToken
      });
      // 默认自动播放
      // playerRef.current.play();
      
      // v0.1.4
      playerRef.current.event.on("videoInfo", (info) => {
        console.log("videoInfo", info);
      });
    }
  };

  const handleInIt = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.destroy();
      playerRef.current = null;
    }
    createPlayer();
  }, []);

  const handlePlay = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.play();
    }
  }, []);

  const handlePause = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.pause();
    }
  }, []);

  const handleDestroy = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.destroy();
      playerRef.current = null;
    }
  }, []);

  const handleFullscreen = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.fullscreen();
    }
  }, []);

  const handleExitFullscreen = useCallback(() => {
    if (playerRef.current) {
      playerRef.current.exitFullscreen();
    }
  }, []);

  const handleGetVersion = useCallback(() => {
    if (playerRef.current) {
      console.log(playerRef.current.getVersion());
    }
  }, []);

  return (
    <div>
      <div id="player-container" ref={containerRef}></div>
      <div>
        <div>
          <input
            style={{ width: 600 }}
            placeholder="输入播放地址"
            ref={urlRef}
            defaultValue="https://open.ys7.com/v3/openlive/L28647609_1_2.m3u8?expire=1764644823&id=915914456004136960&t=cbad467c0cc2dcafa9e8b663e1fcee506d0ad9863e931d77b4423a25a6e3130&ev=101&supportH265=1"
          />
        </div>
        <div>
          <button onClick={handleInIt}>init</button>
          <button onClick={handlePlay}>播放</button>
          <button onClick={handlePause}>暂停</button>
          <button onClick={handleFullscreen}>开启全屏</button>
          <button onClick={handleExitFullscreen}>取消全屏（ESC）</button>
          <button onClick={handleGetVersion}>获取版本</button>
          <button onClick={handleDestroy}>销毁</button>
        </div>
        <div>
          音量：
          <input ref={volumeRef} placeholder="0-1" />
        </div>
      </div>
    </div>
  );
}

export default Player;
